### ISSUE TITLE
Table vs SQL query performance

### ISSUE THREAD

**Issue by martinstuder** [miraisolutions/sparkbq#2]
It looks like SQL queries are much slower than table queries.

**Comment by xeroquark** [comment]
The 11-second delay was due to a GCP [setting](https://github.com/GoogleCloudPlatform/bigdata-interop/blob/bcc425d177d3c13b8022ff3c1dd178b808ee6ad6/bigquery/src/main/java/com/google/cloud/hadoop/io/bigquery/BigQueryConfiguration.java#L79), which we made it configurable via a previous [commit](https://github.com/miraisolutions/sparkbq/commit/13474bf8b17806f2c19d492483de6fcc4f30d94a).

The slowdown of SQL vs Table stems from the fact that Spotify Spark-BigQuery converts SQL query initially into a temporary table.
